# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Access Token

# Model Form Field configuration
form: $/nizzac/projects/models/accesstoken/fields.yaml

# Model Class name
modelClass: Nizzac\Projects\Models\AccessToken

# Default redirect location
defaultRedirect: nizzac/projects/accesstokens

# Create page
create:
    title: backend::lang.form.create_title
    redirect: nizzac/projects/accesstokens/update/:id
    redirectClose: nizzac/projects/accesstokens

# Update page
update:
    title: backend::lang.form.update_title
    redirect: nizzac/projects/accesstokens
    redirectClose: nizzac/projects/accesstokens

# Preview page
preview:
    title: backend::lang.form.preview_title
