# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Record

# Model Form Field configuration
form: $/nizzac/projects/models/record/fields.yaml

# Model Class name
modelClass: Nizzac\Projects\Models\Record

# Default redirect location
defaultRedirect: nizzac/projects/records

# Create page
create:
    title: backend::lang.form.create_title
    redirect: nizzac/projects/records/update/:id
    redirectClose: nizzac/projects/records

# Update page
update:
    title: backend::lang.form.update_title
    redirect: nizzac/projects/records
    redirectClose: nizzac/projects/records

# Preview page
preview:
    title: backend::lang.form.preview_title
