# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Record

# Model Form Field configuration
form: $/unspun/projects/models/record/fields.yaml

# Model Class name
modelClass: Unspun\Projects\Models\Record

# Default redirect location
defaultRedirect: unspun/projects/records

# Create page
create:
    title: backend::lang.form.create_title
    redirect: unspun/projects/records/update/:id
    redirectClose: unspun/projects/records

# Update page
update:
    title: backend::lang.form.update_title
    redirect: unspun/projects/records
    redirectClose: unspun/projects/records

# Preview page
preview:
    title: backend::lang.form.preview_title
