# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Project

# Model Form Field configuration
form: $/unspun/projects/models/project/fields.yaml

# Model Class name
modelClass: Unspun\Projects\Models\Project

# Default redirect location
defaultRedirect: unspun/projects/projects

# Create page
create:
    title: backend::lang.form.create_title
    redirect: unspun/projects/projects/update/:id
    redirectClose: unspun/projects/projects

# Update page
update:
    title: backend::lang.form.update_title
    redirect: unspun/projects/projects
    redirectClose: unspun/projects/projects

# Preview page
preview:
    title: backend::lang.form.preview_title
