# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Project

# Model Form Field configuration
<<<<<<< HEAD
form: $/impelling/projects/models/project/fields.yaml

# Model Class name
modelClass: Impelling\Projects\Models\Project

# Default redirect location
defaultRedirect: impelling/projects/projects
=======
form: $/unspun/projects/models/project/fields.yaml

# Model Class name
modelClass: Unspun\Projects\Models\Project

# Default redirect location
defaultRedirect: unspun/projects/projects
>>>>>>> add-access-tokens

# Create page
create:
    title: backend::lang.form.create_title
<<<<<<< HEAD
    redirect: impelling/projects/projects/update/:id
    redirectClose: impelling/projects/projects
=======
    redirect: unspun/projects/projects/update/:id
    redirectClose: unspun/projects/projects
>>>>>>> add-access-tokens

# Update page
update:
    title: backend::lang.form.update_title
<<<<<<< HEAD
    redirect: impelling/projects/projects
    redirectClose: impelling/projects/projects
=======
    redirect: unspun/projects/projects
    redirectClose: unspun/projects/projects
>>>>>>> add-access-tokens

# Preview page
preview:
    title: backend::lang.form.preview_title
