# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Project

# Model Form Field configuration
form: $/nizzac/projects/models/project/fields.yaml

# Model Class name
modelClass: Nizzac\Projects\Models\Project

# Default redirect location
defaultRedirect: nizzac/projects/projects

# Create page
create:
    title: backend::lang.form.create_title
    redirect: nizzac/projects/projects/update/:id
    redirectClose: nizzac/projects/projects

# Update page
update:
    title: backend::lang.form.update_title
    redirect: nizzac/projects/projects
    redirectClose: nizzac/projects/projects

# Preview page
preview:
    title: backend::lang.form.preview_title
